package Bomberman;

public enum BombermanType {
    PLAYER, BOMB, PHYSIC_BLOCK, FLAME, WALL, BRICK, PORTAL,
    POWERUP_BOMBS, POWERUP_FLAMES, POWERUP_SPEED, POWERUP_FLAMEPASS, POWERUP_LIFE,
    ENEMY1,ENEMY2,ENEMY3,ENEMY4,ENEMY5,
    CLASSICBOMB, LAZERBOMB, LIGHTBOMB
}
